# -*- coding: utf-8 -*-
"""1st TS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IMR-YaFFVrZLXPcuOK56E58ikCVlexU4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
data=pd.read_csv("/content/LBMA-SILVER.csv")

data.head()

data.plot()

import pandas as pd
import matplotlib.pyplot as plt

# Sample data
data = {
    "Date": ["2022-04-21", "2022-04-20", "2022-04-19", "2022-04-14", "2022-04-13"],
    "High": [24.645, 25.200, 25.915, 25.655, 25.640],
    "Low": [18.87, 19.30, 19.89, 19.54, 19.72],
    "Close": [22.61, 23.21, 24.01, 23.53, 23.68],
}

# Convert to DataFrame
df = pd.DataFrame(data)

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set the 'Date' column as the index
df = df.set_index('Date')

# Plot the 'Close' prices
plt.figure(figsize=(10, 6))
plt.plot(df.index, df['Close'], label='Close Prices', marker='o', color='blue')
plt.title('Time Series Plot of Close Prices')
plt.xlabel('Date')
plt.ylabel('Close Price')
plt.grid()
plt.legend()
plt.show()